#!/bin/sh
# pre-commit hook to execute Pester
powershell -noprofile -executionpolicy Unrestricted -Command "Write-Output "Invoking Pester"; Invoke-Pester -Script ./Tests/psSyntaxAndImportValidation.pester.tests.ps1 -EnableExit;"
# Exit to throw the exit code to the git hook
exit