#!/bin/sh
# pre-commit hook to execute Pester
pwsh-preview -noprofile -executionpolicy Unrestricted -Command "Write-Output "Invoking Pester"; Import-Module -Name ./Tests/Pester.Tests.Settings.psm1; Invoke-Pester -Script ./Tests/GeneralValidations/SyntaxValidation.Tests.ps1 -EnableExit;"
# Exit to throw the exit code to the git hook
exit